---
# Configure PHP.ini for Apache environment

- name: configure php-apache - default options
  ini_file: dest=/etc/php5/apache2/php.ini section='{{ item.0.section }}' option='{{ item.1.option }}' value='{{ item.1.value }}'
  with_subelements:
    - php_all_ini_default_options
    - options
  notify:
    - Restart Apache
- name: configure php-apache - user options
  ini_file: dest=/etc/php5/apache2/php.ini section='{{ item.0.section }}' option='{{ item.1.option }}' value='{{ item.1.value }}'
  with_subelements:
    - php_all_ini_user_options
    - options
  notify:
    - Restart Apache

- name: configure php-apache - default options
  ini_file: dest=/etc/php5/apache2/php.ini section='{{ item.0.section }}' option='{{ item.1.option }}' value='{{ item.1.value }}'
  with_subelements:
    - php_apache_ini_default_options
    - options
  notify:
    - Restart Apache
- name: configure php-apache - user options
  ini_file: dest=/etc/php5/apache2/php.ini section='{{ item.0.section }}' option='{{ item.1.option }}' value='{{ item.1.value }}'
  with_subelements:
    - php_apache_ini_user_options
    - options
  notify:
    - Restart Apache